spring:
  application: aiPicturesStore
  profiles:
    active: @spring.profiles.active@
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 2MB
  session:
    store-type: redis
    timeout: 1800

  #允许跨域的地址
  cors:
    allowed-origin-patterns:
      - http://8.162.3.140
      - http://www.oxncloud.top
      - http://localhost:*
      - http://127.0.0.1:*

server:
  port: 8123
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        #        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.oxn.aiPicturesStore.controller

# DashScope 配置
dashscope:
  apiKey: sk-3d14e742252746e6aba673324b64b41d # 替换为你的DashScope API Key
  apiUrl: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation

# 图片访问前缀配置
nginx:
  proxyUrl: http://www.oxncloud.top/cos
