spring:
  application:
    name: picTalk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod
  redis:
    database: 0
    port: 6379
    timeout: 5000
    host: 127.0.0.1
    password:
  servlet:
    multipart:
      max-file-size: 50MB     # 单个文件最大 100MB
      max-request-size: 50MB  # 整个请求最大 100MB（如果只传一个文件，两者可相同）
  session:
    store-type: redis
    timeout: 1800
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

  #允许跨域的地址
  cors:
    allowed-origin-patterns:
      - http://8.162.3.140
      - http://www.oxncloud.top
      - http://localhost:*
      - http://127.0.0.1:*

server:
  port: 8123
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        #        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.oxn.aiPicturesStore.controller

#文件上传地址
file:
  upload-dir: D:/share

# 文件清理配置
cleanup:
  cron: 0 */10 * * * ?

# 图片访问前缀配置
nginx:
  proxyUrl: ${NGINX_PROXY_URL:http://localhost:8123/api}

# 每日AI创建图片/删除图片限制
limit:
  create: 10
  edit: 10

# DashScope 配置 qwen 模型
dashscope:
  apiUrl: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation

# 百度云 AI
baidu:
  url: https://qianfan.baidubce.com/v2/musesteamer/images/generations
  model: musesteamer-air-image
  size: 1328x1328
  n: 1
  promptExtend: true